version: '3.5'

services:
  frontend:
    image: frontend_example
    ports:
      - 5000:5000
    environment:
      API_URL: http://localhost/api
  backend:
    image: backend_example
    ports:
      - 8000:8000
    environment:
      FRONT_URL: http://localhost
      REDIS: redis-cache
      DB_USERNAME: dbuser
      DB_PASSWORD: dbpass
      DB_NAME: mydb
      DB_HOST: database
    depends_on:
      - database
  redis-cache:
    image: redis:latest
  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
  proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

volumes:
  database:
