FROM ubuntu

WORKDIR /app
COPY ./frontend-example-docker /app

RUN apt-get update \
 && apt-get install -y curl \
 && curl -sL https://deb.nodesource.com/setup_10.x | bash \
 && apt install -y nodejs \
 && npm install \
 && apt-get purge -y --auto-remove curl \
 && rm -rf /var/lib/apt/lists/* \
 && useradd -m app \
 && chown -R app:app /app/

USER app

EXPOSE 5000

ENV API_URL=/api

CMD ["sh", "-c", "API_URL=${API_URL} npm start"]
